export const PHOTOS_LOAD_REQUEST = "PHOTOS_LOAD_REQUEST";
export const PHOTOS_LOAD_SUCCESS = "PHOTOS_LOAD_SUCCESS";
export const PHOTOS_LOAD_FAILED = "PHOTOS_LOAD_FAILED";
export const CLEAR_PHOTOSLIST = "CLEAR_PHOTOSLIST";
